version: '3.4'
services:
  mysqldb:
    image: 'mysql:latest'
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
       - farmacia-volume:/var/lib/mysql
    networks:
      - banco
    restart: always
  app:
    build:
      context: .
    ports:
      - '80:8080'
    networks:
      - default
      - banco
    depends_on:
       - mysqldb
    restart: always

volumes:
  farmacia-volume:
networks:
  default:
  banco:
    internal: true


  