spring:
  docker:
    compose:
      enabled: ${DOCKER_COMPOSE:true} #desabilite ao usar para gerar imagens
  datasource:
    url: jdbc:mysql://${DB_HOST:mysqldb}:${DB_PORT:3307}/${DB_NAME:mydatabase}
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:secret}
    hikari:
      maximum-pool-size: 10 # Ajuste o tamanho máximo do pool conforme necessário
  sql:
   init:
     mode: always #always || embedded || never

  jpa:
    hibernate:
      ddl-auto: ${DB_STR:update} # Defina a estratégia de criação/atualização das tabelas (pode ser 'create', 'update', etc.)            
    show-sql: true # Ative para mostrar as consultas SQL no console (útil para depuração)
    defer-datasource-initialization: true # Inicializando dataSource depois da inserção
server:
  port: ${PORT:8080}