name: Build and Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    env:
      GCR_HOST: ${{ secrets.GCR_HOST }}
      GCR_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      GCR_IMAGE: ${{ secrets.GCR_IMAGE }}
      GCR_REGION: ${{ secrets.GCR_REGION }}
      CLOUD_RUN_SERVICE_NAME: ${{ secrets.CLOUD_RUN_SERVICE_NAME }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          
      - name: Configure Docker Credential Helper
        run: |
            gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build -t $GCR_HOST/$GCR_PROJECT/$GCR_IMAGE:$GITHUB_SHA .
          docker push $GCR_HOST/$GCR_PROJECT/$GCR_IMAGE:$GITHUB_SHA
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve \
          -var="credentials_file='${{ secrets.GCP_CREDENTIALS }}'" \
          -var="project=$GCR_PROJECT" \
          -var="region=$GCR_REGION" \
          -var="database_user='${{ secrets.DATABASE_USER }}'" \
          -var="database_user_password='${{ secrets.DATABASE_USER_PASSWORD }}'" \
          -var="service_name=$CLOUD_RUN_SERVICE_NAME" \
          -var="image=$GCR_HOST/$GCR_PROJECT/$GCR_IMAGE:$GITHUB_SHA

      # - name: Deploy to Cloud Run
      #   run: |
      #       gcloud run deploy $CLOUD_RUN_SERVICE_NAME \
      #         --image=$GCR_HOST/$GCR_PROJECT/$GCR_IMAGE:$GITHUB_SHA \
      #         --platform=managed \
      #         --region=$GCR_REGION