name: Build and Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GCR_HOST: "gcr.io"
      GCR_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      GCR_IMAGE: "farmacia-api"
      GCR_REGION: "southamerica-east1-a"
      CLOUD_RUN_SERVICE_NAME: "app"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Build and Push Docker Image
        env:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        run: |
          docker build -t $GCR_HOST/$GCR_PROJECT/$GCR_IMAGE:$GITHUB_SHA .
          docker push $GCR_HOST/$GCR_PROJECT/$GCR_IMAGE:$GITHUB_SHA
        
        
      - name: Deploy to Cloud Run
        run: |
            gcloud run deploy $CLOUD_RUN_SERVICE_NAME \
              --image=$GCR_HOST/$GCR_PROJECT/$GCR_IMAGE:$GITHUB_SHA \
              --platform=managed \
              --region=$GCR_REGION
