name: Build and Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GCR_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          
      - name: Configure Docker Credential Helper
        run: |
            gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.GCR_HOST }}/${{ env.GCR_PROJECT }}/${{ env.GCR_IMAGE }}:$GITHUB_SHA .
          docker push ${{ env.GCR_HOST }}/${{ env.GCR_PROJECT }}/${{ env.GCR_IMAGE }}:$GITHUB_SHA
        
        
      - name: Deploy to Cloud Run
        run: |
            gcloud run deploy ${{ env.CLOUD_RUN_SERVICE_NAME }} \
              --image=${{ env.GCR_HOST }}/${{ env.GCR_PROJECT }}/${{ env.GCR_IMAGE }}:$GITHUB_SHA \
              --platform=managed \
              --region=${{ env.GCR_REGION }}
