name: Build and Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    env:
      GCR_HOST: "gcr.io"
      GCR_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      GCR_IMAGE: "farmacia-api"
      GCR_REGION: "southamerica-east1"
      CLOUD_RUN_SERVICE_NAME: "app"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          
      - name: Configure Docker Credential Helper
        run: |
            gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build -t $GCR_HOST/$GCR_PROJECT/$GCR_IMAGE:$GITHUB_SHA .
          docker push $GCR_HOST/$GCR_PROJECT/$GCR_IMAGE:$GITHUB_SHA
        
        
      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: '$CLOUD_RUN_SERVICE_NAME'
          image: '$GCR_HOST/$GCR_PROJECT/$GCR_IMAGE:$GITHUB_SHA'
        # run: |
        #     gcloud run deploy $CLOUD_RUN_SERVICE_NAME \
        #       --image=$GCR_HOST/$GCR_PROJECT/$GCR_IMAGE:$GITHUB_SHA \
        #       --platform=managed \
        #       --region=$GCR_REGION
