name: Build and Deploy

on:
  push: 
    branches: 
      deploy
  pull_request:
    types:
      - closed
jobs:
  build:
    #if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    env:
      GCR_HOST: ${{ secrets.GCR_HOST }}
      GCR_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      GCR_IMAGE: ${{ secrets.GCR_IMAGE }}
      GCR_REGION: ${{ secrets.GCR_REGION }}
      CLOUD_RUN_SERVICE_NAME: ${{ secrets.CLOUD_RUN_SERVICE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_USER_PASSWORD: ${{ secrets.DATABASE_USER_PASSWORD }}
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          
      - name: Configure Docker Credential Helper
        run: |
            gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build -t $GCR_HOST/$GCR_PROJECT/$GCR_IMAGE:$GITHUB_SHA .
          docker push $GCR_HOST/$GCR_PROJECT/$GCR_IMAGE:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
            gcloud run deploy $CLOUD_RUN_SERVICE_NAME \
              --image=$GCR_HOST/$GCR_PROJECT/$GCR_IMAGE:$GITHUB_SHA \
              --platform=managed \
              --region=$GCR_REGION
